const ADD_VALUE_TO_INPUT = 'ADD_VALUE_TO_INPUT';
const DELETE_VALUE_FROM_INPUT = 'DELETE_VALUE_FROM_INPUT';
const CLEAR_INPUT = 'CLEAR_INPUT';

export { ADD_VALUE_TO_INPUT, DELETE_VALUE_FROM_INPUT, CLEAR_INPUT };
